name: deploy-staging
on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps: 
      - name: Get code access
        uses: actions/checkout@v2.4.3
      - name: Add public key
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan 16.171.53.102 >> ~/.ssh/known_hosts
      - name: Deploy to staging
        uses: easingthemes/ssh-action@v2.1.1
        with:
          ssh-private-key: ${{ secrets.AWS_PRIVATE_KEY }}
          host: 16.171.53.102
          username: ubuntu
          script: |
            cd /var/www/html
            git clone https://github.com/dmitrygorbatikov/posts-admin.git
            cd posts-admin
            npm install pnpm -g
            pnpm install
            pnpm run build
