name: Test Posts Admin
on: workflow_dispatch
jobs:
  runs-on: ubuntu-latest
  steps: 
    - name: Get access to code
      uses: actions/checkout@v3
    - name: Install dependencies
      run: npm ci
    - name: Run tests
      run: npm run test
